// <auto-generated />
using CvWebApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CvWebApp.Migrations
{
    [DbContext(typeof(MainDBContext))]
    [Migration("20260120185522_SeedMovies")]
    partial class SeedMovies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CvWebApp.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "OnModelCreatingDescription1",
                            Title = "OnModelCreatingTitle1",
                            Url = "OnModelCreatingUrl1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "OnModelCreatingDescription2",
                            Title = "OnModelCreatingTitle2",
                            Url = "OnModelCreatingUrl2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "OnModelCreatingDescription3",
                            Title = "OnModelCreatingTitle3",
                            Url = "OnModelCreatingUrl3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
